# Generated by Django 3.1 on 2020-08-30 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_map_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelno', models.IntegerField()),
                ('blueprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maps.blueprint')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='maps.stage')),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
