# Generated by Django 3.1 on 2020-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200830_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='title',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
